### ISSUE TITLE
About license statement "CC-BY using the MIT License"

### ISSUE THREAD

**Issue by hartwork** [nvkelso/color-oracle-java#15]
Hi!

I just noticed statement "CC-BY using the MIT License" in the readme. Since [CC-BY is a license](https://creativecommons.org/licenses/by/4.0/) *different from* the [MIT license](https://opensource.org/licenses/MIT), that wording does not seem ideal and potentially confusing. What do you think about replacing part "CC-BY using" with "Licensed under"?

Thanks and best, Sebastian

**Comment by nvkelso** [comment]
Sounds good. Want to submit a PR?

**Comment by hartwork** [comment]
Can do, give me a few minutes :+1:
