### ISSUE TITLE
Add black and white?

### ISSUE THREAD

**Issue by abeboparebop** [nvkelso/color-oracle-java#2]
Love the program. I use it for preparing figures in scientific articles, and it would be useful to have a black-and-white overlay in addition to the various color blindness overlays (for the fogies who still print out articles to read and annotate).

Is this interesting and useful, or does it represent feature creep relative to your mission? If the former, there's an off chance I might be able to work on implementing this, though no guarantees. :) I also have no expertise on the algorithms one might use (my first thought is to do a simple average of the RGB values, but that may not be optimal).

**Comment by alanhoyle** [comment]
@abeboparebop: that algorithm would not be great.  There are various better methods of converting to grayscale, http://www.tannerhelland.com/3643/grayscale-image-algorithm-vb6/. I don't know enough about the biology/physiology to know what method or tweaked parameters would best represent vision for total colorblindness.

**Comment by berniejenny** [comment]
Color Oracle 1.3 now includes a grayscale mode.
